### ISSUE TITLE
Accidentally removed pambase from the system

### ISSUE THREAD

**Issue by zdavatz** [gentoo/pambase#4]
I accidentally removed `pambase` from the system. What are the steps to reinstall it? Note: I could remove it with no kind of warning. Normally if it is a system relevant package that I want to remove I get several warnings that the package is system relevant.

**Comment by Zlogene** [comment]
> I accidentally removed `pambase` from the system. What are the steps to reinstall it?


just use any bootable media to mount your system there, then chroot, then reinstall
> Note: I could remove it with no kind of warning. Normally if it is a system relevant package that I want to remove I get several warnings that the package is system relevant.

Gentoo may be run without pam at all (as the most of linux distros), although it will devoid your system of 90% of login functionality (login hardening, cpu resources management per user, efficient passwords management, NSS, ldap, kerberos, 2fa, <long list>), and no, not all packages which are system-wide producing you a warning on removal, just these which belong to the system@ set, and system set exists as a "packages most relevant for the most of systems". 
Next time you should be more careful, especially if you are not sure about what is being removed.

**Comment by zdavatz** [comment]
> > I accidentally removed `pambase` from the system. What are the steps to reinstall it?
> 
> just use any bootable media to mount your system there, then chroot, then reinstall

Can I just reinstall pambase?

**Comment by Zlogene** [comment]
> > > I accidentally removed `pambase` from the system. What are the steps to reinstall it?
> > 
> > 
> > just use any bootable media to mount your system there, then chroot, then reinstall
> 
> Can I just reinstall `pambase`?

yes, it only affects files in the `/etc/pam.d` directory

**Comment by zdavatz** [comment]
> yes, it only affects files in the `/etc/pam.d` directory

Could I also manually edit the files if I chroot into the system? Which files did `emerge -C pambase` actually remove?

**Comment by zdavatz** [comment]
There should at least be a warning that the removal of `pambase` will lock you out of your system. This has never happened to me in the last 20 years. Actually I had a conflict telling me that `pam` and `pambase` can not be installed at the same time. That is why I removed `pambase`.

**Comment by Zlogene** [comment]
> > yes, it only affects files in the `/etc/pam.d` directory
> 
> Could I also manually edit the files if I chroot into the system?

You can, but you must have full understanding of every line in every file in the /etc/pam.d directory, a  _single_ mistake in  _any_ file in the directory can make your system inaccessible

> Which files did `emerge -C pambase` actually remove?

Essentially these ones

``` * Contents of sys-auth/pambase-20201103:
/etc
/etc/pam.d
/etc/pam.d/login
/etc/pam.d/other
/etc/pam.d/passwd
/etc/pam.d/su
/etc/pam.d/system-auth
/etc/pam.d/system-local-login
/etc/pam.d/system-login
/etc/pam.d/system-remote-login
/etc/pam.d/system-services
```

**Comment by Zlogene** [comment]
> There should at least be a warning that the removal of `pambase` will lock you out of your system. This has never happened to me in the last 20 years. Actually I had a conflict telling me that `pam` and `pambase` can not be installed at the same time. That is why I removed `pambase`.

The conflict is weird, because ```pambase``` installs the files ```pam``` is actually reading to let your applications work correctly.
Something has gone terribly wrong on your system.

**Comment by zdavatz** [comment]
Yes the circular dependencies deserve a special please in hell. ;) - it was a result of trying to upgrade perl, which again relied on make dbus up-gradable. https://bugs.funtoo.org/browse/FL-7931

**Comment by thesamesam** [comment]
You should not use -C to resolve issues in general.

**Comment by zdavatz** [comment]
I know that. But sometimes it is the only thing that helps. A Blocker is a Blocker.

**Comment by thesamesam** [comment]
Only hard blockers require that and _even then_, you can usually get out of it by nudging an upgrade of something.

**Comment by zdavatz** [comment]
Yes, I was suprised, because before that I done `emerge -C readline` and that gave a me solid system warning "belongs to core system, do you really want to remove?" in beautiful yellow and red. I removed version `readline 6` and re-emerged version 8. All sweet including the solid warning.

**Comment by zdavatz** [comment]
Do I have to reset all my passwords or will they be the same after I do `emerge pambase` again?

**Comment by Zlogene** [comment]
> Do I have to reset all my passwords or will they be the same after I do `emerge pambase` again?

No, your passwords are stored in the `/etc/shadow` file, that is provided bu the totally different package.

**Comment by zdavatz** [comment]
Thank you. Back up and working. Please implement that warning.

**Comment by zdavatz** [comment]
This may be off-topic but how would you guys solve this problem:

![latest-screenshot](https://user-images.githubusercontent.com/4953/104440014-1cb2d400-5592-11eb-9b40-ef3874b042ee.png)

Without having to do `emerge -C` either for `postgresql-8.4.17` or for `eselect-postgresql-2.4`?

**Comment by thesamesam** [comment]
@zdavatz Could we see the full output of emerge -p -uvDU @world?

**Comment by zdavatz** [comment]
sure:
```
These are the packages that would be merged, in order:

Calculating dependencies... done!

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-libs/openssl:0

  (dev-libs/openssl-1.1.1g:0/1.1.1g::core-kit, ebuild scheduled for merge) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (dev-libs/openssl-1.0.2k:0/0::gentoo, installed) pulled in by
    dev-libs/openssl:0/0= required by (dev-lang/python-2.7.18:2.7/2.7::python-kit, installed)
                    ^^^^^
    (and 1 more with the same problem)

dev-libs/icu:0

  (dev-libs/icu-67.1:0/67.1::core-kit, ebuild scheduled for merge) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (dev-libs/icu-58.2-r1:0/58.2::core-kit, installed) pulled in by
    >=dev-libs/icu-51.2-r1:0/58.2=[-mgorny(-)] required by (dev-libs/libxml2-2.9.10-r1:2/2::core-kit, installed)
                          ^^^^^^^^

NOTE: Use the '--verbose-conflicts' option to display parents omitted above

It may be possible to solve this problem by using package.mask to
prevent one of those packages from being selected. However, it is also
possible that conflicting dependencies exist such that they are
impossible to satisfy simultaneously.  If such a conflict exists in
the dependencies of two different packages, then those packages can
not be installed simultaneously.

For more information, see MASKED PACKAGES section in the emerge man
page or refer to the Gentoo Handbook.


The following USE changes are necessary to proceed:
 (see "package.use" in the portage(5) man page for more details)
# required by dev-lang/php-7.4.14::core-server-kit[apache2]
# required by dev-php/PEAR-Net_SMTP-1.8.1::core-server-kit
# required by @selected
# required by @world (argument)
>=www-servers/apache-2.4.46 apache2_modules_unixd
# required by media-gfx/graphviz-2.44.1::media-kit
# required by media-gfx/imagemagick-7.0.8.49::media-kit[graphviz]
# required by @selected
# required by @world (argument)
>=media-libs/gd-2.3.0 jpeg truetype fontconfig

 * In order to avoid wasting time, backtracking has terminated early
 * due to the above autounmask change(s). The --autounmask-backtrack=y
 * option can be used to force further backtracking, but there is no
 * guarantee that it will produce a solution.

emerge: there are no ebuilds built with USE flags to satisfy ">=dev-ruby/rubygems-1.8.10-r1[ruby_targets_ruby19]".
!!! One of the following packages is required to complete your request:
- dev-ruby/rubygems-3.2.0::ruby-kit (Missing IUSE: ruby_targets_ruby19)
- dev-ruby/rubygems-3.1.5::ruby-kit (Missing IUSE: ruby_targets_ruby19)
- dev-ruby/rubygems-3.1.4::ruby-kit (Missing IUSE: ruby_targets_ruby19)
- dev-ruby/rubygems-3.0.9::ruby-kit (Missing IUSE: ruby_targets_ruby19)
- dev-ruby/rubygems-3.0.8::ruby-kit (Missing IUSE: ruby_targets_ruby19)
- dev-ruby/rubygems-3.0.3::ruby-kit (Missing IUSE: ruby_targets_ruby19)
(dependency required by "dev-lang/ruby-1.9.3_p429::gentoo" [installed])
(dependency required by "@selected" [set])
(dependency required by "@world" [argument])
```
@thesamesam do have have github sponsorship page? If not not please consider setting one up so people like me can sponsor you.
