### ISSUE TITLE
system-auth template misspells "try_first_pass" in sys-auth/pambase-20210201

### ISSUE THREAD

**Issue by creideiki** [gentoo/pambase#6]
`try_first_pass` has two 's':es, not one:
https://github.com/gentoo/pambase/blob/fbbc2d49c860857b2fe4b2a6cdb967b0867261c9/templates/system-auth.tpl#L15

After upgrading to sys-auth/pambase-20210201, this fills syslog with these error messages:
```
pam_unix(sshd:setcred): unrecognized option [try_first_pas]
```

**Comment by thesamesam** [comment]
On it, thank you!
